### ISSUE TITLE
Repo link not auto-checked at submission

### ISSUE THREAD

**Issue by GeertvanGeest** [sib-swiss/glittr#15]
If repos are submitted with the 'contribute' button and the maintainer accepts the submission the repository url isn't auto-checked for being a github/gitlab repository, resulting in empty records.

**Comment by yhaefligsib** [comment]
This was intentional and mentioned in the text so the form can also being used as a contact form for someone just wanting to send a message.

![image](https://github.com/sib-swiss/glittr/assets/118164920/257b4ead-70d4-46a0-aec7-918c16604a64)

If you prefer I can change the text on the left to point people to the email for contact and put back the URL validation in the form?

**Comment by GeertvanGeest** [comment]
Ah, yes of course .. Apologies!
I think that would be a better option indeed. Up till now I only received genuine submissions, or empty ones (none with questions/remarks).

**Comment by yhaefligsib** [comment]
Merged live #21
